### ISSUE TITLE
Add search for docs

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#185]

**Comment by ngokevin** [comment]
What tools/services do you have in mind? Algolia?

**Comment by cvan** [comment]
lunr I'm familiar and comfortable with. could use a third-party etc.

to set up, add this to `_config.yml`:

```yaml 
# Lunr
## https://github.com/o2team/hexo-generator-lunr
## http://lunrjs.com/
lunr:
  field: all
  fulltext: true
  path: lunr/
```
